# Generated by Django 3.1.3 on 2020-11-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0022_shipping_method_channel_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="maximum_delivery_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="minimum_delivery_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
